// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions não tem suporte para esta plataforma.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJB3V1721u-HyCDxRLwVASlCcRbe4Lw_w',
    appId: '1:1050487724825:android:cbbd0b37bfe6fd84e30388',
    messagingSenderId: '1050487724825',
    projectId: 'magnum-bank-test',
    storageBucket: 'magnum-bank-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDb6hEKWPoreGvFOP171L-sYxac11ya54',
    appId: '1:1050487724825:ios:f6eb48e09533d651e30388',
    messagingSenderId: '1050487724825',
    projectId: 'magnum-bank-test',
    storageBucket: 'magnum-bank-test.firebasestorage.app',
    iosClientId: '1:1050487724825:ios:f6eb48e09533d651e30388',
    iosBundleId: 'com.magnumbank',
  );

}
